global:
  #scrape_interval:     15s
  #evaluation_interval: 15s
  scrape_interval:     5s
  evaluation_interval: 5s
  scrape_timeout:      5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
 - job_name: pushgateway
   honor_labels: true
   static_configs:
    - targets:
      #- ${PUSHGATEWAY_HOST:pushgateway}:${PUSHGATEWAY_PORT:9091}
      - pushgateway:9091

 
